### PR TITLE
Enforce linting and tests

### PR DESCRIPTION
**Pull request by vaaralav**
Are these hooks welcome?

* Add precommit hook: lint
* Add prepush hook: lint & test
* Fix linter errors and warnings

### CODE REVIEW

**Comment by jussiarpalahti** [comment]
@vaaralav I don't see problems with these hooks
There's one odd-looking conflict in package.json which I hope you can find the time to fix :/

**Comment by jussiarpalahti** [comment]
Are these changes I see more to do with linter doing syntax changes, BTW?

**Comment by vaaralav** [comment]
@jussiarpalahti I didn't manually fix the lint errors. Instead I ran the files with lint errors through Prettier. Is the output of Prettier ok to you?

**Comment by jussiarpalahti** [comment]
Um, I meant that there's lot's of changes in this PR which seem to be from running linter?
In addition of setting those hooks.

**Comment by vaaralav** [comment]
Ah! The hooks prevent commits if linting throws errors so I had to fix the errors 😉

**Comment by jussiarpalahti** [comment]
Okei, well, reading commit this big isn't as smooth as one would like, but let's go with this.

**Comment by Ta1Nur** [comment]
Good this PR seems to be ready soon, thank you

**Comment by Ta1Nur** [comment]
@jussiarpalahti is this PR ready?

**Comment by jussiarpalahti** [comment]
I thought I merged this, but apparently not...

**Pull request merged**
