### PR TITLE
chore: e2e tests oh-29

### PR DESCRIPTION
**Pull request by terovirtanen**
## Description

Add Playwright end-to-end tests

## Related Issue(s)

**[OH-29](https://helsinkisolutionoffice.atlassian.net/browse/OH-29)**

## Screenshots / Videos

[OH-29]: https://helsinkisolutionoffice.atlassian.net/browse/OH-29?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr515-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr515-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mikkojamG — COMMENTED** [review]
Seems to work as expected, great! 👍  I noticed that Typescript has also been installed. As of now TS has not been used anywhere else in the code. Although our future goal is to use Typescript in all FE projects, I think we could come back to this as a individual task and leave it out for now.. 🤔

**Comment by terovirtanen** [comment]
> Seems to work as expected, great! 👍 I noticed that Typescript has also been installed. As of now TS has not been used anywhere else in the code. Although our future goal is to use Typescript in all FE projects, I think we could come back to this as a individual task and leave it out for now.. 🤔

Typescript has been added as a devDependency. The reason is an error in the tests
https://github.com/City-of-Helsinki/helerm-ui/actions/runs/7272453805/job/19814602102

> `Run yarn test --coverage
yarn run v1.22.21
$ react-scripts test --watchAll=false --verbose --coverage
/home/runner/work/helerm-ui/helerm-ui/node_modules/resolve/lib/sync.js:113
    throw err;
    ^

> Error: Cannot find module 'typescript' from '/home/runner/work/helerm-ui/helerm-ui/node_modules'`

**Review by mikkojamG — APPROVED** [review]
LGTM 👍

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr515-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr515-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr515-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
