### PR TITLE
feat: replace CRA with Vite TIED-129

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description

First one out of two pull requests. [Second pull request](https://github.com/City-of-Helsinki/helerm-ui/pull/512)

In order to start using V3 HDS components webpack should include some Node.js polyfills. This would require ejecting the CRA Webpack configuration, but I figured we might as well replace Webpack with Vite right away.

## Related Issue(s)

**[TIED-129](https://helsinkisolutionoffice.atlassian.net/browse/TIED-129)**

## How Has This Been Tested?

Testing on local machine and running with Docker.

## Screenshots / Videos

[TIED-129]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr511-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr511-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr511-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr511-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]
Looks good

**Comment by Riippi** [comment]
Sonar complains about test coverage, but it's not possible to test changes in conf and test files.

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr511-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr511-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
