### PR TITLE
deps: upgrade Vite dependencies TIED-164

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description
Upgrading Vite dependencies and rollup@^4.22.4 as a resolution. This update fixes multiple vulnerabilities:
- https://github.com/City-of-Helsinki/helerm-ui/security/dependabot/95
- https://github.com/City-of-Helsinki/helerm-ui/security/dependabot/99
- https://github.com/City-of-Helsinki/helerm-ui/security/dependabot/100
- https://github.com/City-of-Helsinki/helerm-ui/security/dependabot/101
- https://github.com/City-of-Helsinki/helerm-ui/security/dependabot/102

## Related Issue(s)

**[TIED-164](https://helsinkisolutionoffice.atlassian.net/browse/TIED-164)**

## Screenshots / Videos

[TIED-164]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr551-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr551-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr551-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr551-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr551-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr551-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
