### PR TITLE
Enhanced dropdowns

### PR DESCRIPTION
**Pull request by villeristi**
Use [react-select](https://github.com/JedWatson/react-select) as a drop-in replacement for `select`

### CODE REVIEW

**Comment by jonraem** [comment]
`clearable ` => false

**Comment by villeristi** [comment]
@jonraem fixed =>

**Comment by jonraem** [comment]
Changing dropdown values doesn't update state

**Comment by jonraem** [comment]
Travis CI builds fail, otherwise fine

**Comment by villeristi** [comment]
Ok, build now passes. Going to merge this in.

**Pull request merged**
