### PR TITLE
 deps: remove eslint-config-react-app TIED-164

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description
Remove eslint-config-react-app. Not using CRA anymore, so not really necessary reason to keep it around. Had to make some adjustments to eslint configs and some component and style fixes. This update removes vulnerable micromatch version:
- https://github.com/City-of-Helsinki/helerm-ui/security/dependabot/93

## Related Issue(s)

**[TIED-164](https://helsinkisolutionoffice.atlassian.net/browse/TIED-164)**

## Screenshots / Videos

[TIED-164]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr550-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr550-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr550-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr550-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr550-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr550-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Pull request merged**
