### PR TITLE
Feature/#99 refactor expired token recovery

### LINKED ISSUE #99: IE11 "Next day" Issue - prevent opening front page when token not valid
Related issue https://github.com/City-of-Helsinki/helerm-ui/issues/16
In Finnish https://tree.taiga.io/project/juyrjola-tiedonohjausjarjestelma/issue/258

Tried to figure out current code 
https://github.com/jussiarpalahti/helerm-ui

### PR DESCRIPTION
**Pull request by vaaralav**
Fixes #99 and IE11 logout issues.

### CODE REVIEW

**Comment by Ta1Nur** [comment]
What is this PR status -- have you discussed about this solution? Cannot find comments about it in GH or Slack ping @jussiarpalahti

**Comment by jussiarpalahti** [comment]
Could you, @vaaralav, perhaps elaborate with sentence and two what has changed here? Merely looking at code changes I can't quite get how this behaves when token has expired.

**Comment by vaaralav** [comment]
@jussiarpalahti the issue was actually caused by Internet Explorer aborting logout redirect within AJAX call (something like this https://stackoverflow.com/questions/36448574/ajax-request-with-cors-redirect-fails-in-ie11 ). That error was uncaught so the state and token in local storage were never cleared. Expired token aka `HTTP 401` response to API request started the logout flow which then failed in IE and left app state in "loading" state.

I discussed this issue with @juyrjola and it turned out that SSO logout shouldn't be implemented with AJAX. This PR implements logout with browser navigation instead of AJAX call.

Changing the logout implementation fixes the automatic logout when API responds with status `401` for expired or invalid token.

**Comment by jussiarpalahti** [comment]
Well, yes, but how does this handle browser is used again after weekend and token has expired in the meantime? At least explicit logout doesn't then happen. Is there automatic "logout" done somewhere or otherwise done removal of authenticated state?

Anyway, I'll have to merge this since currently we can't test this otherwise...

**Comment by vaaralav** [comment]
Ah I see what you mean (how come I was so blind :D ). Just a minute, I'll make a new PR.

**Pull request merged**
