### PR TITLE
fix: dropdown fixing clicking outside TIED-154

### PR DESCRIPTION
**Pull request by mikkojamG**
## Description

Fixing bug where clicking outside does not currently close the dropdown.

## Related Issue(s)

**[TIED-154](https://helsinkisolutionoffice.atlassian.net/browse/TIED-154)**

## Screenshots / Videos

[TIED-154]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr531-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr531-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr531-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr531-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr531-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr531-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by Riippi — APPROVED** [review]
👍

**Pull request merged**
