### PR TITLE
fix: 141 show attributes bug

### PR DESCRIPTION
**Pull request by timwessman**
## Description

Fixes bug of metadata not visible

## Related Issue(s)

**[TIED-141](https://helsinkisolutionoffice.atlassian.net/browse/TIED-141)**

## How Has This Been Tested?

How to test instructions in Jira ticket

[PR test environment](https://tiedonohjaus-pr526-ui.dev.hel.ninja/)

[TIED-141]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr526-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __failed__ for https://tiedonohjaus-pr526-ui.dev.hel.ninja :crying_cat_face::anger::boom::boom:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr526-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
## e2e tests result is __success__ for https://tiedonohjaus-pr526-ui.dev.hel.ninja :laughing::tada::tada::tada:

**Review by mikkojamG — APPROVED** [review]
👍

**Pull request merged**
