### PR TITLE
build: remove useless pipelines

### PR DESCRIPTION
**Pull request by terovirtanen**
## Description

Remove old pipelines that are not used anymore

## Related Issue(s)

**[TIED-138](https://helsinkisolutionoffice.atlassian.net/browse/TIED-138)**

## Screenshots / Videos

[TIED-138]: https://helsinkisolutionoffice.atlassian.net/browse/TIED-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr505-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr505-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr505-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**TIEDONOHJAUS-UI branch is deployed to platta: https://tiedonohjaus-pr505-ui.dev.hel.ninja** :rocket::rocket::rocket:

**Review by voneiden — APPROVED** [review]
noice review environment

**Pull request merged**
